import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "./(components)/layout/Layout";
import Motion from "./(components)/motion/motion";
import TopleftImg from "./(components)/topleftimg/TopleftImg";
import { Nav } from "./(components)/nav/Nav";
import Header from "./(components)/header/Header";
import { AnimatePresence } from "framer-motion";
import Transition from "./(components)/transition/Transition";
import Avatar from "./(components)/avatar/Avatar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};[]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Motion>
              {children}
            
        </Motion>
      </body>
    </html>
  );
}
